# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0012_user_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', height_field=200, upload_to='documents/', width_field=200),
        ),
    ]
