# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0014_auto_20170221_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profilepics/%Y/%m/%d/'),
        ),
    ]
