# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0015_auto_20170222_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_list',
            new_name='videotitle',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='', upload_to='videos/%Y/%m/%d/'),
        ),
    ]
