# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0017_auto_20170307_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='\\LoginPage\\images\\default.jpg', upload_to='profilepics/%Y/%m/%d/'),
        ),
    ]
