# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0018_auto_20170329_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
